using BankApp.Core.Customers.Events;
using BankApp.Core.Models;
using BankApp.Core.Repositories;
using MediatR;

namespace BankApp.Core.Customers.Commands.WithdrawCommand;

public record WithdrawCommand(Guid Id, decimal Amount) : IRequest<bool> { }
internal class WithdrawCommandHandler : IRequestHandler<WithdrawCommand, bool>
{
    private readonly ICustomerRepository _customerRepository;
    private readonly IEventRepository _eventRepository;

    public WithdrawCommandHandler(ICustomerRepository customerRepository, IEventRepository eventRepository)
    {
        _customerRepository = customerRepository;
        _eventRepository = eventRepository;
    }

    public async Task<bool> Handle(WithdrawCommand request, CancellationToken cancellationToken)
    {
        IEnumerable<IEvent> events = await _eventRepository.GetAllByAggregateId(request.Id);

        Customer customer = Customer.LoadFromEvents(request.Id, events);

        customer.Withdraw(request.Amount);

        // Get the withdrawal event generated by the Withdraw method
        var withdrawalEvent = customer.GetPendingEvents().OfType<FundsWithdrawnEvent>().FirstOrDefault();

        if (withdrawalEvent != null)
        {
            // Store the withdrawal event in the event repository
            await _eventRepository.Add(withdrawalEvent);

            // Clear pending events after storing
            customer.ClearPendingEvents();

            // Deduct the withdrawal amount from the customer's balance in the data store
            if (await _customerRepository.DeductFromBalance(request.Id, request.Amount))
            {
                return true;
            }
        }

        return false;
    }
}